name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: bokuweb/reg-actions@master
        with:
          secret: "${{ secrets.GITHUB_TOKEN }}"
          actual-directory-path: "actual"
      - uses: actions/upload-artifact@v1
        with:
          name: reg
          path: __reg__
