name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: bokuweb/reg-actions@fix-image-copy
        with:
          secret: "${{ secrets.GITHUB_TOKEN }}"
          image-directory-path: "actual"
